# Generated by Django 4.1.1 on 2022-11-09 21:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.CharField(max_length=1000)),
                ('insta', models.CharField(max_length=1000)),
                ('yt', models.CharField(max_length=1000)),
                ('twt', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('brief', tinymce.models.HTMLField()),
                ('time', models.TimeField(default=datetime.datetime(2022, 11, 9, 21, 11, 25, 408672, tzinfo=datetime.timezone.utc))),
                ('url', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='news/')),
                ('img2', models.ImageField(default='default.png', upload_to='news/')),
                ('img3', models.ImageField(default='default.png', upload_to='news/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
        ),
    ]
